version: '3'
services:
  lyrist:
    build: .
    restart: unless-stopped
    container_name: "lyrist"
    image: lyrist:latest
    expose:
      - "3000"
    ports:
      - "3001:3000"
    volumes:
      - ./:/app